language: R
sudo: required
cache: packages
latex: none

#warnings_are_errors: true
before_install:
    - sudo apt-get install -y udunits-bin libudunits2-dev
    - sudo apt-get -qq update
    - tlmgr install index
    #LaTeX- tlmgr install hyperref


r:
    - release
    #- devel

r_packages:
    - devtools
    - covr

# Custom R CMD ------------------
script:
    - R CMD build --no-build-vignettes .
    - R CMD check *tar.gz
# Custom R CMD ------------------

after_success:
    - Rscript -e 'covr::codecov()'

